// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // Cursos
    public class Curso
    {
        public int IdCurso { get; set; } // IdCurso (Primary key)
        public string Titulo { get; set; } // Titulo (length: 100)
        public int IdInstructor { get; set; } // idInstructor
        public DateTime? FechaCreacion { get; set; } // FechaCreacion
        public DateTime? FechaModificacion { get; set; } // FechaModificacion
        public int? Interesados { get; set; } // Interesados
        public int? Estudiantes { get; set; } // Estudiantes
        public int IdEstado { get; set; } // IdEstado
        public bool Destacado { get; set; } // Destacado

        // Reverse navigation

        /// <summary>
        /// Child UsuariosCursoes where [UsuariosCursos].[IdCurso] point to this entity (FK_UsuariosCursos_Curso)
        /// </summary>
        public virtual ICollection<UsuariosCurso> UsuariosCursoes { get; set; } // UsuariosCursos.FK_UsuariosCursos_Curso

        // Foreign keys

        /// <summary>
        /// Parent Estado pointed by [Cursos].([IdEstado]) (FK_Cursos_Estados)
        /// </summary>
        public virtual Estado Estado { get; set; } // FK_Cursos_Estados

        /// <summary>
        /// Parent Instructore pointed by [Cursos].([IdInstructor]) (FK_Cursos_Instructores)
        /// </summary>
        public virtual Instructore Instructore { get; set; } // FK_Cursos_Instructores

        public Curso()
        {
            FechaCreacion = DateTime.Now;
            FechaModificacion = DateTime.Now;
            Interesados = 0;
            Estudiantes = 0;
            IdEstado = 1;
            Destacado = false;
            UsuariosCursoes = new List<UsuariosCurso>();
        }
    }

}
// </auto-generated>
