// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    // Estados
    public class Estado
    {
        public int IdEstado { get; set; } // IdEstado (Primary key)
        public string Descripcion { get; set; } // Descripcion (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Cursoes where [Cursos].[IdEstado] point to this entity (FK_Cursos_Estados)
        /// </summary>
        public virtual ICollection<Curso> Cursoes { get; set; } // Cursos.FK_Cursos_Estados

        public Estado()
        {
            Cursoes = new List<Curso>();
        }
    }

}
// </auto-generated>
