// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public interface IMyDbContext : IDisposable
    {
        DbSet<Curso> Cursoes { get; set; } // Cursos
        DbSet<Estado> Estadoes { get; set; } // Estados
        DbSet<InfoAcademia> InfoAcademias { get; set; } // InfoAcademia
        DbSet<Instructore> Instructores { get; set; } // Instructores
        DbSet<Pais> Pais { get; set; } // Paises
        DbSet<PreguntasFreq> PreguntasFreqs { get; set; } // PreguntasFreq
        DbSet<Usuario> Usuarios { get; set; } // Usuarios
        DbSet<UsuariosCurso> UsuariosCursoes { get; set; } // UsuariosCursos

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }
}
// </auto-generated>
