// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ClassLibrary1
{
    // InfoAcademia
    public class InfoAcademiaConfiguration : IEntityTypeConfiguration<InfoAcademia>
    {
        public void Configure(EntityTypeBuilder<InfoAcademia> builder)
        {
            builder.ToTable("InfoAcademia", "dbo");
            builder.HasKey(x => x.IdAcademia).HasName("PK__InfoAcad__A68DEE39E9D66049").IsClustered();

            builder.Property(x => x.IdAcademia).HasColumnName(@"IdAcademia").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
        }
    }

}
// </auto-generated>
