// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    // InfoAcademia
    public class InfoAcademia
    {
        public int IdAcademia { get; set; } // IdAcademia (Primary key)
    }

}
// </auto-generated>
