// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ClassLibrary1
{
    // Instructores
    public class InstructoreConfiguration : IEntityTypeConfiguration<Instructore>
    {
        public void Configure(EntityTypeBuilder<Instructore> builder)
        {
            builder.ToTable("Instructores", "dbo");
            builder.HasKey(x => x.IdInstructor).HasName("PK__Instruct__10850044525376D5").IsClustered();

            builder.Property(x => x.IdInstructor).HasColumnName(@"IdInstructor").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Nombre).HasColumnName(@"Nombre").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Apellido).HasColumnName(@"Apellido").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Descripción).HasColumnName(@"Descripción").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.IdPais).HasColumnName(@"IdPais").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Pais).WithMany(b => b.Instructores).HasForeignKey(c => c.IdPais).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Instructores_Pais");
        }
    }

}
// </auto-generated>
