// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    // Instructores
    public class Instructore
    {
        public int IdInstructor { get; set; } // IdInstructor (Primary key)
        public string Nombre { get; set; } // Nombre (length: 50)
        public string Apellido { get; set; } // Apellido (length: 50)
        public string Descripción { get; set; } // Descripción
        public int IdPais { get; set; } // IdPais

        // Reverse navigation

        /// <summary>
        /// Child Cursoes where [Cursos].[idInstructor] point to this entity (FK_Cursos_Instructores)
        /// </summary>
        public virtual ICollection<Curso> Cursoes { get; set; } // Cursos.FK_Cursos_Instructores

        // Foreign keys

        /// <summary>
        /// Parent Pais pointed by [Instructores].([IdPais]) (FK_Instructores_Pais)
        /// </summary>
        public virtual Pais Pais { get; set; } // FK_Instructores_Pais

        public Instructore()
        {
            Cursoes = new List<Curso>();
        }
    }

}
// </auto-generated>
