// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ClassLibrary1
{
    // PreguntasFreq
    public class PreguntasFreqConfiguration : IEntityTypeConfiguration<PreguntasFreq>
    {
        public void Configure(EntityTypeBuilder<PreguntasFreq> builder)
        {
            builder.ToTable("PreguntasFreq", "dbo");
            builder.HasKey(x => x.IdPregunta).HasName("PK__Pregunta__754EC09EA6B9C81B").IsClustered();

            builder.Property(x => x.IdPregunta).HasColumnName(@"IdPregunta").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Pregunta).HasColumnName(@"Pregunta").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Respuesta).HasColumnName(@"Respuesta").HasColumnType("nvarchar(max)").IsRequired(false);
        }
    }

}
// </auto-generated>
