// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    // PreguntasFreq
    public class PreguntasFreq
    {
        public int IdPregunta { get; set; } // IdPregunta (Primary key)
        public string Pregunta { get; set; } // Pregunta
        public string Respuesta { get; set; } // Respuesta
    }

}
// </auto-generated>
