// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ClassLibrary1
{
    // UsuariosCursos
    public class UsuariosCursoConfiguration : IEntityTypeConfiguration<UsuariosCurso>
    {
        public void Configure(EntityTypeBuilder<UsuariosCurso> builder)
        {
            builder.ToTable("UsuariosCursos", "dbo");
            builder.HasKey(x => x.Id).HasName("PK__Usuarios__3214EC07DED0A33A").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.IdCurso).HasColumnName(@"IdCurso").HasColumnType("int").IsRequired();
            builder.Property(x => x.IdUsuario).HasColumnName(@"IdUsuario").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Curso).WithMany(b => b.UsuariosCursoes).HasForeignKey(c => c.IdCurso).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UsuariosCursos_Curso");
            builder.HasOne(a => a.Usuario).WithMany(b => b.UsuariosCursoes).HasForeignKey(c => c.IdUsuario).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UsuariosCursos_Usuario");
        }
    }

}
// </auto-generated>
