// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    // UsuariosCursos
    public class UsuariosCurso
    {
        public int Id { get; set; } // Id (Primary key)
        public int IdCurso { get; set; } // IdCurso
        public int IdUsuario { get; set; } // IdUsuario

        // Foreign keys

        /// <summary>
        /// Parent Curso pointed by [UsuariosCursos].([IdCurso]) (FK_UsuariosCursos_Curso)
        /// </summary>
        public virtual Curso Curso { get; set; } // FK_UsuariosCursos_Curso

        /// <summary>
        /// Parent Usuario pointed by [UsuariosCursos].([IdUsuario]) (FK_UsuariosCursos_Usuario)
        /// </summary>
        public virtual Usuario Usuario { get; set; } // FK_UsuariosCursos_Usuario
    }

}
// </auto-generated>
