// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    // Usuarios
    public class Usuario
    {
        public int IdUsuario { get; set; } // IdUsuario (Primary key)
        public string Email { get; set; } // Email (length: 50)
        public DateTime? FechaInscripcion { get; set; } // FechaInscripcion
        public DateTime? UltimoAcceso { get; set; } // UltimoAcceso
        public string Nombre { get; set; } // Nombre (length: 50)
        public string Apellido { get; set; } // Apellido (length: 50)
        public int? IdPais { get; set; } // IdPais
        public string Contraseña { get; set; } // Contraseña (length: 10)

        // Reverse navigation

        /// <summary>
        /// Child UsuariosCursoes where [UsuariosCursos].[IdUsuario] point to this entity (FK_UsuariosCursos_Usuario)
        /// </summary>
        public virtual ICollection<UsuariosCurso> UsuariosCursoes { get; set; } // UsuariosCursos.FK_UsuariosCursos_Usuario

        // Foreign keys

        /// <summary>
        /// Parent Pais pointed by [Usuarios].([IdPais]) (FK_Usuarios_Pais)
        /// </summary>
        public virtual Pais Pais { get; set; } // FK_Usuarios_Pais

        public Usuario()
        {
            FechaInscripcion = DateTime.Now;
            UsuariosCursoes = new List<UsuariosCurso>();
        }
    }

}
// </auto-generated>
