// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ClassLibrary1
{
    // Usuarios
    public class UsuarioConfiguration : IEntityTypeConfiguration<Usuario>
    {
        public void Configure(EntityTypeBuilder<Usuario> builder)
        {
            builder.ToTable("Usuarios", "dbo");
            builder.HasKey(x => x.IdUsuario).HasName("PK__Usuarios__5B65BF9788D26F19").IsClustered();

            builder.Property(x => x.IdUsuario).HasColumnName(@"IdUsuario").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.FechaInscripcion).HasColumnName(@"FechaInscripcion").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.UltimoAcceso).HasColumnName(@"UltimoAcceso").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.Nombre).HasColumnName(@"Nombre").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Apellido).HasColumnName(@"Apellido").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.IdPais).HasColumnName(@"IdPais").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Contraseña).HasColumnName(@"Contraseña").HasColumnType("nchar(10)").IsRequired(false).IsFixedLength().HasMaxLength(10);

            // Foreign keys
            builder.HasOne(a => a.Pais).WithMany(b => b.Usuarios).HasForeignKey(c => c.IdPais).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Usuarios_Pais");
        }
    }

}
// </auto-generated>
